_wandb:
    value:
        cli_version: 0.23.0
        e:
            6lc5dotkxnituef4aym2v2aeifn3f3a2:
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "510455517184"
                        used: "351812198400"
                email: lupereyra699@gmail.com
                executable: C:\Users\59899\Documents\Universidad\7mosemestre\IA\IA\cartpole\.venv\Scripts\python.exe
                git:
                    commit: 605c49e5cba0177c4fcdd1bc92b62d0b7ab58ef3
                    remote: https://github.com/lucia893/IA.git
                host: Lucia
                memory:
                    total: "16558346240"
                os: Windows-10-10.0.26100-SP0
                program: -m src.sweep_run
                python: CPython 3.10.11
                root: C:\Users\59899\Documents\Universidad\7mosemestre\IA\IA\Cartpole
                startedAt: "2025-11-21T01:33:42.948873Z"
                writerId: 6lc5dotkxnituef4aym2v2aeifn3f3a2
        m: []
        python_version: 3.10.11
        t:
            "3":
                - 2
                - 16
            "4": 3.10.11
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
agent:
    value: ql
alpha:
    value: 0.1
disc:
    value: uniform
disc_data_episodes:
    value: 50
episodes:
    value: 800
eps_decay:
    value: 0.995
eps_end:
    value: 0.02
eps_start:
    value: 1
gamma:
    value: 0.99
k_subset:
    value: 1
seed:
    value: 42
